### ISSUE TITLE
viewify init not running

### ISSUE THREAD

**Issue by danielbaak** [scriptnull/sails-viewify#3]
Hi,

I've followed the readme to a 't' and am getting

```
➜  viewify-test  sails-viewify init
: No such file or directory
```

for context, I'm using

```
➜  ~  npm --version
2.14.4 (as well as 3.3.5)
➜  ~  node --version
v4.1.1
➜  ~  sails --version
0.11.0
```

Is there something I can do to get some debugging output?

The command 
    node node_modules/sails-viewify/index.js init
silently succeeds, which is confusing.

**Comment by scriptnull** [comment]
Have you created `sails-viewify.js` configuration file inside the `config` folder of the sails project ?

Also , don't forget to install sails-viewify globally. 

``` bash
npm install -g sails-viewify
```

**Comment by danielbaak** [comment]
Yes, and yes.

Seems like it's not installing sails-viewify globally properly. Tried this on two different machines (linux mint 17.01 and ubuntu 14.04)

➜  ~  sails-viewify --version
module.js:338
    throw err;
    ^

Error: Cannot find module '/home/user/node_modules/sails-viewify/index.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Function.Module.runMain (module.js:475:10)
    at startup (node.js:117:18)
    at node.js:951:3

**Comment by scriptnull** [comment]
I am using Windows for developing sails-viewify . But , it should work on linux too. However , I haven't tried it yet on linux machines. So , I will try out and get back to you. Until then , Could you please try these steps and share the outputs here. 
- Try  installing as root

``` bash
sudo npm install -g sails-viewify
```

I hope , you have tried this already , still , I would like to mention it . 
- Navigate to `node_modules/sails-viewify` or git clone this repo and execute `npm install -g`. sails-viewify must be installed at this point. If not , share your results.

**Comment by danielbaak** [comment]
Thanks for taking the time to look into this. 

It refuses to run no matter how it's installed (locally / globally (with or without root)).

`node ./node_modules/sails-viewify/index.js init`
generated the files it's supposed to, but 
`node ./node_modules/sails-viewify/index.js User UserDetails.ejs`
silently fails (i.e. no files are generated).

The global version of sails-viewify always states 
    ➜  sails-viewify-test  sails-viewify 
    : No such file or directory
which most likely referes to `index.js` which it seems to look for in the wrong place. No idea why.

**Comment by jup31** [comment]
Hello everybody,

I have the same issue on ubuntu 14.04, and even if I modify index.js to display an error on the first line of code, I have exactly the same error. So I think it come from the first line #!/usr/bin/env node
If I do `echo $PATH` it returns :
`/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`
I have node on /usr/bin : `ls /usr/bin | grep node` it returns : 
`node
nodejs`

Thanks for any help.

**Comment by jup31** [comment]
The solution running locally `index.js` on the project worked for me `node ./node_modules/sails-viewify/index.js init` create a file and 
`node ./node_modules/sails-viewify/index.js User UserDetails.ejs` generate a view after modification of the ./config/sails-viewify.js file.

Any idea how to correct the global install ?

**Comment by scriptnull** [comment]
@jup31 Thanks for the observation. I have fixed the error right now and released `sails-viewify 1.0.4`. You could try installing sails-viewify now.

Refer this [diff](https://github.com/scriptnull/sails-viewify/commit/dcfb27c484cc23ad78b1ed1979bbf4a559c28e1a) , if you would like to know the fix. 

As far as I have tested with `sails-viewify 1.0.4` and `Ubuntu 14.04` . sails-viewify is working properly.

So , I am closing this issue. If you still face issues , please reopen this issue.

**Comment by jup31** [comment]
I confirm it work.

Thanks a lot.

**Comment by jup31** [comment]
I tryed #!/usr/bin/ node but not without the space :( Thanks a lot.

**Comment by scilaci** [comment]
On Windows, if you have this error message 
: No such file or directory

Change the node reference path on these 2 files because they're bad:
- sails-viewify
- sails-viewify.cmd

File location : C:\Users\YourWindowsUser\AppData\Roaming\npm
